services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:

    KimaiPlugin\ApprovalBundle\:
        resource: '../../*'
        exclude:
            - '../../{Resources}'
            - '../../vendor'
            - '../../vendor-bin'

    KimaiPlugin\ApprovalBundle\API\:
        resource: '../../API'
        tags: ['controller.service_arguments']

    approval.settings:
        class: KimaiPlugin\ApprovalBundle\Settings\MetaFieldSettings

    KimaiPlugin\ApprovalBundle\Settings\ApprovalSettingsInterface:
        alias: 'approval.settings'
