name: CI
on:
    pull_request: null
    push:
        branches:
            - master
jobs:
    tests:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php: ['7.4', '8.0', '8.1', '8.2', '8.3']

        name: Linting - PHP ${{ matrix.php }}
        steps:
            -   uses: actions/checkout@v2
            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    coverage: none
                    extensions: intl, gd, zip
            -   run: composer install --no-progress
            -   run: composer validate --strict --no-check-version
            -   run: composer codestyle-check
            -   run: composer phpstan
